import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NODE_ENV: z
      .enum(["development", "test", "production"])
      .default("development"),
    DATABASE_URL: z.string().url(),
    GOOGLE_CLIENT_ID: z.string().min(1),
    GOOGLE_CLIENT_SECRET: z.string().min(1),
    SMTP_HOST: z.string().min(1),
    SMTP_FROM_EMAIL: z.string().min(1),
    SMTP_USERNAME: z.string().min(1),
    SMTP_PORT: z.string().min(1),
    RESEND_API_KEY: z.string().min(1),
    DB_MIGRATING: z.boolean().default(false),
    DB_SEEDING: z.boolean().default(false),
    VAPI_API_KEY: z.string().min(1),
    STRIPE_PUBLISHABLE_KEY: z.string().min(1),
    STRIPE_SECRET_KEY: z.string().min(1),
    STRIPE_WEBHOOK_SECRET: z.string().min(1),
    UPSTASH_REDIS_REST_TOKEN: z.string().min(1),
    UPSTASH_REDIS_REST_URL: z.string().min(1),
    // PAYSTACK_SECRET_KEY: z.string().min(1),
    SENDGRID_API_KEY: z.string().min(1),
  },
  client: {
    NEXT_PUBLIC_URL: z.string().url(),
    NEXT_PUBLIC_VAPI_API_KEY: z.string(),
    NEXT_PUBLIC_VAPI_CLIENT_SDK: z.string(),
    NEXT_PUBLIC_ADORA_AI: z.string(),
  },
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    DATABASE_URL: process.env.DATABASE_URL,
    DB_MIGRATING: process.env.DB_MIGRATING === "true",
    DB_SEEDING: process.env.DB_SEEDING === "true",
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    NEXT_PUBLIC_URL: process.env.NEXT_PUBLIC_URL,
    SMTP_HOST: process.env.SMTP_HOST,
    SMTP_FROM_EMAIL: process.env.SMTP_FROM_EMAIL,
    SMTP_USERNAME: process.env.SMTP_USERNAME,
    SMTP_PORT: process.env.SMTP_PORT,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
    VAPI_API_KEY: process.env.VAPI_API_KEY,
    NEXT_PUBLIC_VAPI_API_KEY: process.env.NEXT_PUBLIC_VAPI_API_KEY,
    NEXT_PUBLIC_VAPI_CLIENT_SDK: process.env.NEXT_PUBLIC_VAPI_CLIENT_SDK,
    NEXT_PUBLIC_ADORA_AI: process.env.NEXT_PUBLIC_ADORA_AI,
    STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    // PAYSTACK_SECRET_KEY: process.env.PAYSTACK_SECRET_KEY,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
  },
});
