#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling your project before committing👷‍♂️🏗️'
echo 'please be patient, this may take a while...'


pnpm run lint ||
(
   echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
         Run yarn lint, add changes and try commit again.';
   false;
)

#Check TypeScript Compilation
pnpm run tsc --noEmit ||
(
   echo '🔨❌ Yoo, you have TypeScript errors in your code. Fix them 🔨❌
         Run pnpm tsc, add changes and try commit again.';
   false;
)

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'

npx lint-staged