name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_SECURE: ${{ secrets.SMTP_SECURE }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_FROM_EMAIL: ${{ secrets.SMTP_FROM_EMAIL }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      VAPI_API_KEY: ${{ secrets.VAPI_API_KEY }}
      NEXT_PUBLIC_VAPI_API_KEY: ${{ secrets.NEXT_PUBLIC_VAPI_API_KEY }}
      NEXT_PUBLIC_VAPI_CLIENT_SDK: ${{ secrets.NEXT_PUBLIC_VAPI_CLIENT_SDK }}
      NEXT_PUBLIC_ADORA_AI: ${{ secrets.NEXT_PUBLIC_ADORA_AI }}
      PAYSTACK_SECRET_KEY: ${{ secrets.PAYSTACK_SECRET_KEY }}
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install package dependencies
        run: pnpm install

      - name: Check linting and formatting
        run: pnpm run lint

      - name: Execute build
        run: pnpm run build
