name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout to the repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment using the version in .nvmrc
      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc" # Reads Node.js version from .nvmrc

      # Step 3: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Cache pnpm store
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Step 5: Install dependencies using pnpm
      - name: Install package dependencies
        run: pnpm install

      # Step 6: Check linting and formatting
      - name: Check linting and formatting
        run: pnpm run lint

      # Step 7: Execute build
      - name: Execute build
        run: pnpm run build
